version: '3.5'

services:
  flask-api:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
        - .:/app
    ports:
      - "5000:5000"

  redis:
    image: "redis:alpine"

        #  rabbitmq:
        #    image: rabbitmq:3.7.15-management-alpine
        #    environment:
        #      - RABBITMQ_DEFAULT_USER=hellofresh
        #      - RABBITMQ_DEFAULT_PASS=food
        #    ports:
        #      - "5672:5672"
        #      - "15672:15672"
        # 
        #  prometheus:
        #    image: prom/prometheus:latest
        #    restart: unless-stopped
        #    container_name: prometheus
        #    ports:
        #      - 9090:9090
        #    volumes:
        #      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
        #    command:
        #      - '--config.file=/etc/prometheus/prometheus.yml'
        # 
        #  grafana:
        #    image: grafana/grafana:latest
        #    restart: unless-stopped
        #    user: "472"
        #    container_name: grafana
        #    depends_on:
        #      - prometheus
        #    ports:
        #      - 3000:3000
        #    volumes:
        #      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasource.yml
        #    env_file:
        #      - ./monitoring/config.monitoring
        # 
